project_id = "fvxzmmtbptwooznxlfji"

[functions.transcribe-audio]
verify_jwt = false

[functions.generate-pv]
verify_jwt = false

[functions.tts-pv]
verify_jwt = false

[functions.parse-template]
verify_jwt = false

[functions.analyze-meeting]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false
